services:
  chatbot-nodejs:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    restart: always
    ports:
      - "3000:3002"
    volumes:
      - .:/app                    # Sync code into container for development
      - /app/node_modules         # Prevent local node_modules overwrite
      - ./logs:/app/logs
    depends_on:
      redis:
        condition: service_healthy
    environment:
      - NODE_ENV=development
      - PORT=3002
      - REDIS_URL=redis://redis:6379
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=${REDIS_PASSWORD:-admin}
    command: npm run dev          # Use nodemon for auto-reload

  redis:
    image: redis:8-alpine
    restart: always
    ports:
      - "6380:6379"
    command: redis-server --requirepass ${REDIS_PASSWORD} --bind 0.0.0.0
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
volumes:
  redis_data:
